### PR TITLE
Refactoring + content/embeds at the same time

### PR DESCRIPTION
**Pull request by yutamago**
I did a few things:
- refactoring (see changes for details)
- actually working tests
- allowing content and embeds at the same time (very useful when you want mention a role or a user, because that's impossible inside embeds)
- provide examples for YAML configuration
- documentation
- updated the dependencies
- removed deprecated dependencies
- setting version to 2.0.0 and extension to `@2` because of breaking changes in the inputs
- set license to MIT and add missing LICENSE file

Please review and tell me if there's something you're uncomfortable with.
Would love to see this merged.

### CODE REVIEW

**Comment by yutamago** [comment]
@seraphx2 hey, any progress on reviewing this?

Waiting for a few more days. After that I guess I'm free to publish my own fork as a new extension.

**Comment by seraphx2** [comment]
@yutamago will this cause breaking changes with fields like the channel id and maybe losing the value entirely? Should I maybe make a 2.0 so that it doesn't get automatically updated in people's task pipelines and then maybe break?

**Comment by yutamago** [comment]
> Should I maybe make the version 2.0

Definitely needs a version 2.0 / `@2`!
I thought I already did that, but I might've missed it somewhere.
I ran the tests but didnt try it out in a live environment yet.

Breaking changes:
- channelId is now webhookId
  I thought it was misleading to name it channelId, because I found the channelId to be different some cases and it lead to errors. 
  In the discord API docs it's also called webhookId.
- messageType was removed
  There is no reason to choose either content or embed. You can now use both at the same time.

**Comment by seraphx2** [comment]
Oh, i see. yeah, I thought you had as well, but figured I was imagining things.
however, there are three places to change it, and the vss-extensions.json file manages the output file naming.
you changed it in the task.json, and then for everything to match, i change the package.json file as well. lol

I'll commit this and upload a 2.0.0 extension.

**Comment by seraphx2** [comment]
It's sort of hard to test these sometimes. I think you can deploy directly to a single organization, but it's sort of a pain...lol
Crash and Burn.  lol
but at least since it's 2.0 it won't hurt anyone else.
2.0.0 is deployed, so, i guess you can test it live? haha

**Comment by yutamago** [comment]
Okay, there's still some issues:

- Getting the following error in my log, because I removed the *.js files (because they're generated on build and are therefore redundant).
Will add them back shortly and think of a better solution later:
`##[error]File not found: '/home/vsts/work/_tasks/ado-discord-webhook_fd1d030f-d11a-4246-bb0e-3d64a84f714f/2.0.0/index.js'`
- The labels are missing for content and embeds, not sure yet why, but I'll try to figure it out:
image

**Pull request merged**
